services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: zzz
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: