-- AlterTable
ALTER TABLE "Character" ALTER COLUMN "map" SET DEFAULT 'magirita',
ALTER COLUMN "energy" SET DEFAULT 10,
ALTER COLUMN "agility" SET DEFAULT 10,
ALTER COLUMN "accuracy" SET DEFAULT 10,
ALTER COLUMN "luck" SET DEFAULT 10;
