export interface ItemInventory {
  id_idx: number
  hero_order: number
  serial: string
  item_idx: number
  socket_type: number
  socket_num: number
  count: number
  opt: number
  opt_level: number
  duration?: number
  last_check_time: Date
  synergy?: number
  synergy_level?: number
  s_item: Item
}

export interface Item {
  idx: number
  name: string
  price: number
  barter_price: number
  rarity: number
  type: number
  maxCnt: number
  require_level: number
  require_type: number
  require_value: number
  equip_type: number
  equip_part0: number
  equip_part1: number
  equip_part2: number
  block_part0: number
  block_part1: number
  roll_spell_idx: number
  roll_spell_level: number
  ech_type0: number
  ech_type1: number
  ech_type2: number
  ech_type3: number
  ech_type4: number
  ech_type5: number
  ech_type6: number
  ech_typenum0: number
  ech_typenum1: number
  ech_typenum2: number
  ech_typenum3: number
  ech_typenum4: number
  ech_typenum5: number
  ech_typenum6: number
  ech_x0: number
  ech_x1: number
  ech_x2: number
  ech_x3: number
  ech_x4: number
  ech_x5: number
  ech_x6: number
  ech_speed_move: number
  ech_speed_attack: number
  ech_speed_skill: number
  range: number
  duration: number
  kind: number
  rank: number
  duration_type: number
  restrict_type?: number
  make_synergy_type: number
  make_synergy_level: number
}